# Builds
[tasks.build-starter]
cwd = "."
command = "cargo"
args = ["leptos", "build", "--release", "--precompress", "-vv"]

# Lints
[tasks.lint-starter]
cwd = "."
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.lint-codegen]
cwd = "./codegen"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.lint]
run_task = { name = [
    "lint-starter",
    "lint-codegen",
] }

# Tests
[tasks.unit-tests]
cwd = "."
command = "cargo"
args = ["nextest", "run"]

[tasks.integration-tests]
cwd = "."
script = '''
#!/bin/sh
set +e
cargo leptos build --precompress --release;
target/release/starter &

echo "Up and running";
cd end2end;
npm install;

# This script supports nixos with devenv or ubuntu:24 due to playwright.
if command -v devenv >/dev/null 2>&1
then
    CI=1 devenv shell playwright test;
else
    npx playwright install-deps;
    npx playwright install;
    CI=1 npx playwright test;
fi

# Kills whatever this script spawned
kill $! && echo "killed server";

'''

[tasks.tests]
run_task = { name = [
    "unit-tests",
    "integration-tests"
] }

# Tries to run the same checks as the CI, locally.
[tasks.mimic-ci]
run_task = { name = [
    "lint",
    "tests"
] }